package com.thouraya.a4inshield;


import android.app.Activity;
import android.os.Bundle;


import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;

    public class childdashboard_activity extends Activity {


        private View _bg__childdashboard_ek2;
        private View noise_texture_light_ek11;
        private View dark_color_13_ek11;
        private View top_bar_container;
        private View white_color;
        private View bounds_ek12;
        private ImageView shape_ek15;
        private View bounds_ek13;
        private ImageView shape_ek16;
        private TextView __;
        private TextView designer;
        private TextView rebecca_morgan;
        private View rectangle_172_ek8;
        private ImageView vector_ek148;
        private ImageView vector_ek149;
        private ImageView vector_ek150;
        private ImageView vector_ek151;
        private ImageView vector_ek152;
        private ImageView vector_ek153;
        private ImageView vector_ek154;
        private ImageView vector_ek155;
        private ImageView vector_ek156;
        private ImageView vector_ek157;
        private ImageView vector_ek158;
        private ImageView vector_ek159;
        private ImageView vector_ek160;
        private ImageView vector_ek161;
        private View background_color_ek31;
        private TextView __29_90;
        private TextView text;
        private View background_color_ek32;
        private TextView __29_90_ek1;
        private TextView text_ek1;
        private View background_color_ek33;
        private View background_color_ek34;
        private TextView rebecca_morgan_ek1;
        private TextView _12_34_pm;
        private TextView mama_always_said_lif;
        private View unread_detail;
        private TextView rebecca_morgan_ek2;
        private TextView _12_34_pm_ek1;
        private TextView mama_always_said_lif_ek1;
        private View unread_detail_ek1;
        private TextView __29_90_ek2;
        private TextView text_ek2;
        private ImageView background_color_ek35;
        private TextView __29_90_ek3;
        private TextView text_ek3;
        private View noise_texture_light_ek12;
        private View dark_color_13_ek12;
        private View top_bar_container_ek1;
        private View white_color_ek1;
        private View bounds_ek14;
        private ImageView shape_ek17;
        private TextView ___ek1;
        private View drop_shadow_1;
        private View background_color_ek36;
        private View rectangle_172_ek9;
        private ImageView vector_ek162;
        private ImageView vector_ek163;
        private ImageView vector_ek164;
        private ImageView vector_ek165;
        private ImageView vector_ek166;
        private ImageView vector_ek167;
        private ImageView vector_ek168;
        private ImageView vector_ek169;
        private ImageView vector_ek170;
        private ImageView vector_ek171;
        private ImageView vector_ek172;
        private ImageView vector_ek173;
        private ImageView vector_ek174;
        private ImageView vector_ek175;
        private ImageView combined_shape;
        private ImageView rectangle_23;
        private TextView __29_90_ek4;
        private View drop_shadow_1_ek1;
        private View background_color_ek37;
        private View rectangle_172_ek10;
        private ImageView vector_ek176;
        private ImageView vector_ek177;
        private ImageView vector_ek178;
        private ImageView vector_ek179;
        private ImageView vector_ek180;
        private ImageView vector_ek181;
        private ImageView vector_ek182;
        private ImageView vector_ek183;
        private ImageView vector_ek184;
        private ImageView vector_ek185;
        private ImageView vector_ek186;
        private ImageView vector_ek187;
        private TextView __29_90_ek5;
        private ImageView combined_shape_ek1;
        private ImageView rectangle_23_ek1;
        private View drop_shadow_1_ek2;
        private View background_color_ek38;
        private View rectangle_172_ek11;
        private ImageView vector_ek188;
        private ImageView vector_ek189;
        private ImageView vector_ek190;
        private ImageView vector_ek191;
        private ImageView vector_ek192;
        private ImageView vector_ek193;
        private ImageView vector_ek194;
        private ImageView vector_ek195;
        private ImageView vector_ek196;
        private ImageView vector_ek197;
        private ImageView vector_ek198;
        private ImageView vector_ek199;
        private TextView __29_90_ek6;
        private ImageView combined_shape_ek2;
        private ImageView rectangle_23_ek2;
        private TextView bitcoin;
        private View bottom_nav_container;
        private View white_color_ek2;
        private TextView templates;
        private View bounds_ek15;
        private ImageView rectangle_ek30;
        private TextView templates_ek1;
        private View bounds_ek16;
        private ImageView rectangle_ek31;
        private TextView templates_ek2;
        private View bounds_ek17;
        private ImageView rectangle_ek32;
        private View dark_color_13_ek13;
        private TextView templates_ek3;
        private View bounds_ek18;
        private ImageView rectangle_ek33;
        private View background_ek6;
        private TextView day;
        private TextView week;
        private TextView month;

        @Override
        public void onCreate(Bundle savedInstanceState) {

            super.onCreate(savedInstanceState);
            setContentView(R.layout.childdashboard);



            designer = (TextView) findViewById(R.id.designer);
            rebecca_morgan = (TextView) findViewById(R.id.rebecca_morgan);
            rectangle_172_ek8 = (View) findViewById(R.id.rectangle_172_ek8);
            vector_ek148 = (ImageView) findViewById(R.id.vector_ek148);
            vector_ek149 = (ImageView) findViewById(R.id.vector_ek149);
            vector_ek150 = (ImageView) findViewById(R.id.vector_ek150);
            vector_ek151 = (ImageView) findViewById(R.id.vector_ek151);
            vector_ek152 = (ImageView) findViewById(R.id.vector_ek152);
            vector_ek153 = (ImageView) findViewById(R.id.vector_ek153);
            vector_ek154 = (ImageView) findViewById(R.id.vector_ek154);
            vector_ek155 = (ImageView) findViewById(R.id.vector_ek155);
            vector_ek156 = (ImageView) findViewById(R.id.vector_ek156);
            vector_ek157 = (ImageView) findViewById(R.id.vector_ek157);
            vector_ek158 = (ImageView) findViewById(R.id.vector_ek158);
            vector_ek159 = (ImageView) findViewById(R.id.vector_ek159);
            vector_ek160 = (ImageView) findViewById(R.id.vector_ek160);
            vector_ek161 = (ImageView) findViewById(R.id.vector_ek161);
            background_color_ek31 = (View) findViewById(R.id.background_color_ek31);
            __29_90 = (TextView) findViewById(R.id.__29_90);
            text = (TextView) findViewById(R.id.text);
            background_color_ek32 = (View) findViewById(R.id.background_color_ek32);
            __29_90_ek1 = (TextView) findViewById(R.id.__29_90_ek1);
            text_ek1 = (TextView) findViewById(R.id.text_ek1);
            background_color_ek33 = (View) findViewById(R.id.background_color_ek33);
            background_color_ek34 = (View) findViewById(R.id.background_color_ek34);
            rebecca_morgan_ek1 = (TextView) findViewById(R.id.rebecca_morgan_ek1);
            _12_34_pm = (TextView) findViewById(R.id._12_34_pm);
            mama_always_said_lif = (TextView) findViewById(R.id.mama_always_said_lif);
            unread_detail = (View) findViewById(R.id.unread_detail);
            rebecca_morgan_ek2 = (TextView) findViewById(R.id.rebecca_morgan_ek2);
            _12_34_pm_ek1 = (TextView) findViewById(R.id._12_34_pm_ek1);
            mama_always_said_lif_ek1 = (TextView) findViewById(R.id.mama_always_said_lif_ek1);
            unread_detail_ek1 = (View) findViewById(R.id.unread_detail_ek1);
            __29_90_ek2 = (TextView) findViewById(R.id.__29_90_ek2);
            text_ek2 = (TextView) findViewById(R.id.text_ek2);
            background_color_ek35 = (ImageView) findViewById(R.id.background_color_ek35);
            __29_90_ek3 = (TextView) findViewById(R.id.__29_90_ek3);
            text_ek3 = (TextView) findViewById(R.id.text_ek3);
            noise_texture_light_ek12 = (View) findViewById(R.id.noise_texture_light_ek12);
            dark_color_13_ek12 = (View) findViewById(R.id.dark_color_13_ek12);
            top_bar_container_ek1 = (View) findViewById(R.id.top_bar_container_ek1);
            white_color_ek1 = (View) findViewById(R.id.white_color_ek1);
            bounds_ek14 = (View) findViewById(R.id.bounds_ek14);
            shape_ek17 = (ImageView) findViewById(R.id.shape_ek17);
            ___ek1 = (TextView) findViewById(R.id.___ek1);
            drop_shadow_1 = (View) findViewById(R.id.drop_shadow_1);
            background_color_ek36 = (View) findViewById(R.id.background_color_ek36);
            rectangle_172_ek9 = (View) findViewById(R.id.rectangle_172_ek9);
            vector_ek162 = (ImageView) findViewById(R.id.vector_ek162);
            vector_ek163 = (ImageView) findViewById(R.id.vector_ek163);
            vector_ek164 = (ImageView) findViewById(R.id.vector_ek164);
            vector_ek165 = (ImageView) findViewById(R.id.vector_ek165);
            vector_ek166 = (ImageView) findViewById(R.id.vector_ek166);
            vector_ek167 = (ImageView) findViewById(R.id.vector_ek167);
            vector_ek168 = (ImageView) findViewById(R.id.vector_ek168);
            vector_ek169 = (ImageView) findViewById(R.id.vector_ek169);
            vector_ek170 = (ImageView) findViewById(R.id.vector_ek170);
            vector_ek171 = (ImageView) findViewById(R.id.vector_ek171);
            vector_ek172 = (ImageView) findViewById(R.id.vector_ek172);
            vector_ek173 = (ImageView) findViewById(R.id.vector_ek173);
            vector_ek174 = (ImageView) findViewById(R.id.vector_ek174);
            vector_ek175 = (ImageView) findViewById(R.id.vector_ek175);
            combined_shape = (ImageView) findViewById(R.id.combined_shape);
            rectangle_23 = (ImageView) findViewById(R.id.rectangle_23);
            __29_90_ek4 = (TextView) findViewById(R.id.__29_90_ek4);
            drop_shadow_1_ek1 = (View) findViewById(R.id.drop_shadow_1_ek1);
            background_color_ek37 = (View) findViewById(R.id.background_color_ek37);
            rectangle_172_ek10 = (View) findViewById(R.id.rectangle_172_ek10);
            vector_ek176 = (ImageView) findViewById(R.id.vector_ek176);
            vector_ek177 = (ImageView) findViewById(R.id.vector_ek177);
            vector_ek178 = (ImageView) findViewById(R.id.vector_ek178);
            vector_ek179 = (ImageView) findViewById(R.id.vector_ek179);
            vector_ek180 = (ImageView) findViewById(R.id.vector_ek180);
            vector_ek181 = (ImageView) findViewById(R.id.vector_ek181);
            vector_ek182 = (ImageView) findViewById(R.id.vector_ek182);
            vector_ek183 = (ImageView) findViewById(R.id.vector_ek183);
            vector_ek184 = (ImageView) findViewById(R.id.vector_ek184);
            vector_ek185 = (ImageView) findViewById(R.id.vector_ek185);
            vector_ek186 = (ImageView) findViewById(R.id.vector_ek186);
            vector_ek187 = (ImageView) findViewById(R.id.vector_ek187);
            __29_90_ek5 = (TextView) findViewById(R.id.__29_90_ek5);
            combined_shape_ek1 = (ImageView) findViewById(R.id.combined_shape_ek1);
            rectangle_23_ek1 = (ImageView) findViewById(R.id.rectangle_23_ek1);
            drop_shadow_1_ek2 = (View) findViewById(R.id.drop_shadow_1_ek2);
            background_color_ek38 = (View) findViewById(R.id.background_color_ek38);
            rectangle_172_ek11 = (View) findViewById(R.id.rectangle_172_ek11);
            vector_ek188 = (ImageView) findViewById(R.id.vector_ek188);
            vector_ek189 = (ImageView) findViewById(R.id.vector_ek189);
            vector_ek190 = (ImageView) findViewById(R.id.vector_ek190);
            vector_ek191 = (ImageView) findViewById(R.id.vector_ek191);
            vector_ek192 = (ImageView) findViewById(R.id.vector_ek192);
            vector_ek193 = (ImageView) findViewById(R.id.vector_ek193);
            vector_ek194 = (ImageView) findViewById(R.id.vector_ek194);
            vector_ek195 = (ImageView) findViewById(R.id.vector_ek195);
            vector_ek196 = (ImageView) findViewById(R.id.vector_ek196);
            vector_ek197 = (ImageView) findViewById(R.id.vector_ek197);
            vector_ek198 = (ImageView) findViewById(R.id.vector_ek198);
            vector_ek199 = (ImageView) findViewById(R.id.vector_ek199);
            __29_90_ek6 = (TextView) findViewById(R.id.__29_90_ek6);
            combined_shape_ek2 = (ImageView) findViewById(R.id.combined_shape_ek2);
            rectangle_23_ek2 = (ImageView) findViewById(R.id.rectangle_23_ek2);
            bitcoin = (TextView) findViewById(R.id.bitcoin);
            background_ek6 = (View) findViewById(R.id.background_ek6);
            day = (TextView) findViewById(R.id.day);
            week = (TextView) findViewById(R.id.week);
            month = (TextView) findViewById(R.id.month);


            //custom code goes here

        }
    }
	
	